[package]
name = "rust-housework"
version = "0.0.1"
license = "MIT"
authors = ["3442853561"]

[[bin]]
name = "array"
path = "./src/array.rs"

[[bin]]
name = "deconstruction"
path = "./src/deconstruction.rs"

[[bin]]
name = "display"
path = "./src/display.rs"

[[bin]]
name = "float"
path = "./src/float.rs"

[[bin]]
name = "interception"
path = "./src/interception.rs"

[[bin]]
name = "get_variant"
path = "./src/get_variant.rs"

[[bin]]
name = "palindrome"
path = "./src/palindrome.rs"

[[bin]]
name = "rain"
path = "./src/rain.rs"

[[bin]]
name = "read_clone"
path = "./src/read_clone.rs"

[[bin]]
name = "sametag"
path = "./src/sametag.rs"


[[bin]]
name = "to_string"
path = "./src/to_string.rs"

[[bin]]
name = "typeid"
path = "./src/typeid.rs"

[[bin]]
name = "u8"
path = "./src/u8.rs"
