[package]
name = "rust-housework"
version = "0.0.1"
license = "MIT"
authors = ["3442853561"]

[[bin]]
name = "array"
path = "./src/array.rs"

[[bin]]
name = "interception"
path = "./src/interception.rs"

[[bin]]
name = "palindrome"
path = "./src/palindrome.rs"

[[bin]]
name = "u8"
path = "./src/u8.rs"
